//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chapter()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ChapterID { get; set; }
        public Nullable<int> NovelID { get; set; }
        public Nullable<int> ChapterNumber { get; set; }
        public string ChapterTitle { get; set; }
        [AllowHtml]
        [Required(ErrorMessage = "Thư mục này không được để trống")]
        [Display(Name = "Mô tả")]
        public string Content { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Novel Novel { get; set; }
    }
}
