//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NovelHubEntities : DbContext
    {
        public NovelHubEntities()
            : base("name=NovelHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlacklistedNovel> BlacklistedNovels { get; set; }
        public virtual DbSet<BlacklistedUser> BlacklistedUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<FavoriteNovel> FavoriteNovels { get; set; }
        public virtual DbSet<NovelCategory> NovelCategories { get; set; }
        public virtual DbSet<Novel> Novels { get; set; }
        public virtual DbSet<NovelStatus> NovelStatuses { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
